export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Lux',
  fullName: 'Lux Network',
  description: 'Post-quantum secure, high-performance blockchain infrastructure - Layer-0 for Hanzo (AI Compute) and Zoo (AI/ML Specialization)',
  website: 'https://lux.network',
  github: 'https://github.com/luxfi',
  primaryColor: '#3498DB',
  secondaryColor: '#2980B9',
  accentColor: '#E67E22',
  logo: '/logos/lux-logo.svg',
  papers: [
    // ================================================================
    // Consensus Protocols
    // ================================================================
    {
      id: 'consensus',
      title: 'Lux Consensus',
      subtitle: 'Physics-Inspired Metastable Blockchain Consensus',
      abstract: 'Novel consensus mechanism using physics-inspired metastable dynamics for high-throughput finality.',
      pdfUrl: '/pdfs/lux-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'quantum-consensus',
      title: 'Quantum Consensus',
      subtitle: 'Post-Quantum Cryptography with Dilithium Signatures',
      abstract: 'Implementation of NIST-standardized Dilithium post-quantum signatures for validator consensus, ensuring security against quantum computer attacks.',
      pdfUrl: '/pdfs/lux-quantum-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quantum-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-06-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'pq', 'mldsa'],
    },
    {
      id: 'quasar-consensus',
      title: 'Quasar Consensus',
      subtitle: 'Dual-Certificate Quantum-Secure Finality (BLS + Ringtail)',
      abstract: 'Novel consensus mechanism combining BLS signatures with post-quantum Ringtail signatures for quantum-safe finality with efficient verification.',
      pdfUrl: '/pdfs/lux-quasar-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quasar-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'quasar', 'pq', 'bls', 'finality'],
    },
    {
      id: 'fpc-consensus',
      title: 'FPC Consensus',
      subtitle: 'Fast Probabilistic Consensus with Adaptive Thresholds',
      abstract: 'High-throughput probabilistic consensus protocol with adaptive security thresholds and sub-second finality for optimal performance.',
      pdfUrl: '/pdfs/lux-fpc-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fpc-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-12-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'triple-proof-consensus',
      title: 'Triple-Proof Quantum Finality',
      subtitle: 'BLS + STARK-Aggregated ML-DSA + Ringtail in 248 Bytes per Epoch',
      abstract: 'We present triple-proof quantum finality, a consensus mechanism that achieves simultaneous classical speed, post-quantum security, and validator privacy in 248 bytes per epoch. Combines BLS12-381 aggregate signatures, STARK-aggregated ML-DSA-65 signatures, and Ringtail lattice-based threshold signatures. Benchmarks show 357us epoch finality on commodity hardware.',
      pdfUrl: '/pdfs/lux-triple-proof-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-triple-proof-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'pq', 'bls', 'mldsa', 'finality', 'zk'],
    },
    {
      id: 'quasar-benchmarks',
      title: 'Quasar Consensus: Comparative Benchmark Study',
      subtitle: 'Post-Quantum BFT vs Tendermint, HotStuff, Narwhal, Ethereum PoS, Solana, Avalanche',
      abstract: 'Comprehensive benchmark evaluation of Quasar against six production consensus systems: Tendermint/CometBFT, HotStuff/LibraBFT, Narwhal+Tusk, Ethereum PoS, Solana Tower BFT, and Avalanche Snow. Measurements span finality time, transaction throughput, and more.',
      pdfUrl: '/pdfs/lux-quasar-benchmarks.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quasar-benchmarks.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'quasar', 'pq', 'finality'],
    },
    {
      id: 'field-protocol',
      title: 'Field Protocol: Electromagnetic-Inspired Distributed Consensus',
      subtitle: 'Validator Preferences as Dipoles in a Vector Field',
      abstract: 'Consensus mechanism inspired by electromagnetic field theory that models validator preferences as dipoles in a vector field and convergence as field alignment through mutual interaction.',
      pdfUrl: '/pdfs/lux-field-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-field-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'flare-protocol',
      title: 'Flare Protocol: Certificate Skip Exclusivity with Honest Support',
      subtitle: 'Conviction-Based Consensus in DAG Structures',
      abstract: 'Conviction-based consensus mechanism introducing the certificate/skip paradigm for finality in DAG-structured transaction sets. Extends the Slush stochastic sampling primitive with a conviction counter.',
      pdfUrl: '/pdfs/lux-flare-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-flare-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'nebula-protocol',
      title: 'Nebula Protocol: Probabilistic Finality in Sparse Networks',
      subtitle: 'Consensus for Sparse Validator Networks with Partial Reachability',
      abstract: 'Consensus mechanism designed for sparse validator networks where the number of reachable peers may be significantly less than the total validator set. Handles geographically distributed deployments, network partitions, and low-connectivity scenarios.',
      pdfUrl: '/pdfs/lux-nebula-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-nebula-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'nova-protocol',
      title: 'Nova Protocol: Supernova Burst Consensus',
      subtitle: 'High Throughput via Simultaneous DAG Vertex Finalization',
      abstract: 'DAG-based consensus engine achieving high throughput through supernova bursts: batches of vertices finalized simultaneously when a confidence cascade propagates through the DAG.',
      pdfUrl: '/pdfs/lux-nova-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-nova-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'photon-protocol',
      title: 'Photon Protocol: Zero-Latency Consensus Pipelining',
      subtitle: 'Overlapping Sampling Rounds for Multiple Transactions',
      abstract: 'Pipelined binary consensus engine achieving zero-latency overhead by overlapping sampling rounds for multiple transactions. In standard metastable consensus, each transaction occupies sequential rounds; Photon eliminates this bottleneck.',
      pdfUrl: '/pdfs/lux-photon-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-photon-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'prism-protocol',
      title: 'Prism Protocol: Multi-Spectrum Parallel Consensus',
      subtitle: 'Independent Frequency Bands for Concurrent Transaction Processing',
      abstract: 'Multi-spectrum parallel consensus engine that decomposes the consensus problem into independent frequency bands processed concurrently. Assigns each transaction to a spectrum band based on its conflict set hash.',
      pdfUrl: '/pdfs/lux-prism-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-prism-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'ray-protocol',
      title: 'Ray Protocol: Adaptive Finality with Light-Speed Confirmation',
      subtitle: 'Dynamic Parameter Adjustment Based on Network Conditions',
      abstract: 'Adaptive consensus mechanism that dynamically adjusts finality parameters based on observed network conditions to achieve minimum possible confirmation latency -- the light-speed bound determined by network propagation delay.',
      pdfUrl: '/pdfs/lux-ray-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ray-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'wave-protocol',
      title: 'Wave Protocol: Decision Stability and Confidence Monotonicity',
      subtitle: 'Metastable Consensus in DAG-Based Transaction Structures',
      abstract: 'Metastable consensus mechanism achieving decision stability through confidence monotonicity in directed acyclic graph transaction structures. Extends the Slush stochastic sampling primitive with persistent confidence counters.',
      pdfUrl: '/pdfs/lux-wave-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-wave-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    // ================================================================
    // Cryptography & Post-Quantum
    // ================================================================
    {
      id: 'ntt',
      title: 'NTT Transform',
      subtitle: '85% Gas Reduction for Post-Quantum Crypto on EVM',
      abstract: 'Number Theoretic Transform optimization for post-quantum algorithms (FALCON, Dilithium, STARKs) achieving massive gas savings.',
      pdfUrl: '/pdfs/lux-ntt-transform.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ntt-transform.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-05-15',
      authors: ['Lux Industries'],
      tags: ['pq', 'evm', 'precompile'],
    },
    {
      id: 'ethfalcon',
      title: 'ETHFALCON',
      subtitle: 'Post-Quantum FALCON Signatures for Ethereum',
      abstract: 'Optimized implementation of FALCON post-quantum signatures for Ethereum, enabling quantum-safe transactions.',
      pdfUrl: '/pdfs/lux-ethfalcon-post-quantum.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ethfalcon-post-quantum.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-07-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'lattice'],
    },
    {
      id: 'ringtail-pq',
      title: 'Ringtail: Lattice-Based Post-Quantum Threshold Signatures',
      subtitle: 't-of-n Validators Sign Without Full Secret Key Reconstruction',
      abstract: 'Lattice-based post-quantum threshold signature scheme designed for blockchain consensus. Enables t-of-n validators to collaboratively sign blocks without any single party possessing the full secret key, while providing post-quantum security.',
      pdfUrl: '/pdfs/lux-ringtail-pq.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ringtail-pq.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'lattice', 'threshold', 'mpc'],
    },
    {
      id: 'pq-crypto-suite',
      title: 'Post-Quantum Cryptographic Suite as EVM Precompiles',
      subtitle: 'ML-KEM (FIPS 203), ML-DSA (FIPS 204), SLH-DSA (FIPS 205) at 50K-150K Gas',
      abstract: 'Suite of NIST post-quantum cryptographic algorithms implemented as native EVM precompiles: ML-KEM for key encapsulation, ML-DSA for digital signatures, and SLH-DSA for stateless hash-based signatures. Precompile approach reduces costs to 50,000-150,000 gas versus >10M gas for Solidity implementations.',
      pdfUrl: '/pdfs/lux-pq-crypto-suite.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-pq-crypto-suite.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'mldsa', 'evm', 'precompile', 'lattice'],
    },
    {
      id: 'pq-migration',
      title: 'Post-Quantum Migration Strategy',
      subtitle: 'Three-Phase Transition from Classical to Post-Quantum Cryptography',
      abstract: 'Three-phase migration strategy for transitioning production blockchain networks from classical to post-quantum cryptography. Phase 1: hybrid signatures (ECDSA/BLS + ML-DSA). Phase 2: post-quantum primary with classical fallback. Phase 3: classical deprecation. Formalizes crypto agility -- the ability to add, replace, or remove cryptographic algorithms without hard fork.',
      pdfUrl: '/pdfs/lux-pq-migration.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-pq-migration.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'mldsa', 'bls', 'security'],
    },
    {
      id: 'hybrid-pq-architecture',
      title: 'Hybrid Post-Quantum Cryptographic Architecture',
      subtitle: 'BLS12-381 + ML-DSA via Dual-Signature and Key-Combiner Constructions',
      abstract: 'Hybrid cryptographic architecture combining classical elliptic curve primitives (BLS12-381, ECDH on Curve25519) with NIST post-quantum standards (ML-DSA FIPS 204, ML-KEM FIPS 203) via dual-signature and key-combiner constructions. Core security property is compositional resilience: an attacker must break both classical and post-quantum components simultaneously.',
      pdfUrl: '/pdfs/lux-hybrid-pq-architecture.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-hybrid-pq-architecture.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'bls', 'mldsa', 'lattice'],
    },
    {
      id: 'hybrid-certificates',
      title: 'Hybrid X.509 Certificates for Validator Identity',
      subtitle: 'Dual ECDSA/BLS + ML-DSA Signatures in a Single Certificate Chain',
      abstract: 'Hybrid X.509 certificate infrastructure for validator identity combining classical ECDSA/BLS signatures with post-quantum ML-DSA signatures in a single certificate chain. Trust anchors rooted in Q-Chain governance with on-chain registration and revocation via stake-weighted voting.',
      pdfUrl: '/pdfs/lux-hybrid-certificates.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-hybrid-certificates.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'mldsa', 'security'],
    },
    {
      id: 'crypto-agility',
      title: 'Cryptographic Agility Architecture',
      subtitle: 'Live Rotation of Signature Schemes and Hash Functions Without Chain Halts',
      abstract: 'Cryptographic agility architecture enabling live rotation of signature schemes, hash functions, and key encapsulation mechanisms without chain halts, state migration, or consensus forks. Introduces versioned key schedules, algorithm negotiation at the validator handshake layer, and a hybrid classical-post-quantum transition path.',
      pdfUrl: '/pdfs/lux-crypto-agility.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-crypto-agility.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'security'],
    },
    {
      id: 'quantum-threat-blockchain',
      title: 'Quantum Threat Model for Blockchain Infrastructure',
      subtitle: 'Full Attack Surface Beyond Signature Forgery',
      abstract: 'Systematic threat model for quantum computing attacks against blockchain infrastructure. Enumerates the full attack surface: mempool public key exposure, validator signature forgery, retroactive chain compromise via historical transaction replay, bridge key extraction, and oracle manipulation through forged attestations.',
      pdfUrl: '/pdfs/lux-quantum-threat-blockchain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quantum-threat-blockchain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'security'],
    },
    // ================================================================
    // Threshold Signatures & MPC
    // ================================================================
    {
      id: 'threshold-signatures',
      title: 'Universal Threshold Signatures',
      subtitle: 'Unified Framework (CMP, FROST, LSS, Doerner, Ringtail)',
      abstract: 'Comprehensive threshold signature framework supporting multiple protocols including post-quantum Ringtail.',
      pdfUrl: '/pdfs/lux-universal-threshold-signatures.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-universal-threshold-signatures.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-01',
      authors: ['Lux Industries', 'Vishnu Seesahai'],
      tags: ['threshold', 'mpc', 'pq'],
    },
    {
      id: 'threshold-mpc',
      title: 'Unified Threshold Cryptography for Omnichain Custody',
      subtitle: 'FROST, CGGMP21, and Taproot Integration',
      abstract: 'Complete treatment of the threshold signature system: FROST (Ed25519/Schnorr) for 14 chain families, CGGMP21 (ECDSA) for 6 chain families, Bitcoin Taproot via KeygenTaproot. Includes 9 theorems, 3 lemmas, 8 algorithms, formal unforgeability proofs.',
      pdfUrl: '/pdfs/lux-threshold-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-threshold-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2021-02-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['threshold', 'mpc', 'pq'],
      relatedLinks: [
        { label: 'luxfi/threshold (Go)', url: 'https://github.com/luxfi/threshold' },
        { label: 'luxfi/mpc (Go)', url: 'https://github.com/luxfi/mpc' },
        { label: 'FROST Precompile', url: 'https://github.com/luxfi/standard/tree/main/src/precompiles/frost' },
      ],
    },
    {
      id: 'lss-mpc',
      title: 'LSS: Linear Shamir\'s Secret Sharing for MPC',
      subtitle: 'Dynamic Threshold Signatures with Live Secret Resharing',
      abstract: 'Pragmatic MPC framework wrapping CGGMP21 (threshold ECDSA) and FROST (threshold Schnorr/EdDSA) under a unified interface with live membership changes. Coordinator-driven verifiable resharing via JVSS enables transition from (t, n) to (t\', n +/- k) without reconstructing the master key.',
      pdfUrl: '/pdfs/lux-lss-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-lss-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-01-01',
      authors: ['Vishnu Seesahai', 'Zach Kelling'],
      tags: ['threshold', 'mpc', 'pq'],
      relatedLinks: [
        { label: 'luxfi/threshold (Go)', url: 'https://github.com/luxfi/threshold' },
        { label: 'luxfi/mpc (Go)', url: 'https://github.com/luxfi/mpc' },
      ],
    },
    {
      id: 'validator-mpc',
      title: 'Threshold Cryptography for Validator Networks',
      subtitle: 'CGGMP21 + FROST + Ringtail for Validator Signing',
      abstract: 'Threshold cryptographic framework for blockchain validator networks where no individual validator holds a complete signing key. Employs CGGMP21 for ECDSA threshold signing (secp256k1 compatible), FROST for Schnorr/EdDSA, and Ringtail for post-quantum threshold signatures.',
      pdfUrl: '/pdfs/lux-validator-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-validator-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['threshold', 'mpc', 'pq'],
    },
    // ================================================================
    // FHE (Fully Homomorphic Encryption)
    // ================================================================
    {
      id: 'tfhe',
      title: 'Torus Threshold FHE: Boolean Circuits with Distributed Decryption',
      subtitle: 'Threshold TFHE for t-of-n Distributed Decryption',
      abstract: 'Threshold variant of Torus Fully Homomorphic Encryption (TFHE) enabling evaluation of arbitrary boolean circuits on encrypted bits with distributed decryption across t-of-n parties. Encrypts individual bits as Learning With Errors samples.',
      pdfUrl: '/pdfs/lux-tfhe.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tfhe.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'lattice', 'threshold'],
    },
    {
      id: 'fhe-api',
      title: 'Lux FHE API and Developer Model',
      subtitle: 'Go API for Lattice-Based FHE with SIMD-Optimized NTT',
      abstract: 'Go API and developer model for Lux FHE, an original lattice-based fully homomorphic encryption implementation built on luxfi/lattice. Provides boolean gate evaluation on encrypted bits with programmable bootstrapping, radix-decomposed encrypted integers (uint8-uint256), and SIMD-optimized NTT.',
      pdfUrl: '/pdfs/lux-fhe-api.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-api.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'lattice'],
    },
    {
      id: 'fhe-benchmarks',
      title: 'Lux FHE Performance Benchmarks',
      subtitle: '2.1M Polynomial Multiplications/sec, 12ms Boolean AND with Bootstrapping',
      abstract: 'Performance benchmarks for Lux FHE, a pure Go lattice-based fully homomorphic encryption implementation with SIMD-optimized NTT. Covers key generation, encryption/decryption throughput, boolean gate evaluation, radix integer arithmetic, ciphertext serialization, and noise growth. NTT SIMD engine achieves 2.1M polynomial multiplications per second on M2.',
      pdfUrl: '/pdfs/lux-fhe-benchmarks.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-benchmarks.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'lattice'],
    },
    {
      id: 'fhe-mpc-hybrid',
      title: 'FHE-MPC Hybrid Architecture',
      subtitle: 'Trustless Private Computation via TFHE + FROST Threshold Decryption',
      abstract: 'Hybrid cryptographic architecture combining FHE and MPC for trustless private computation. FHE handles encrypted computation while MPC distributes the decryption key via threshold secret sharing. Demonstrated on a private orderbook matching engine achieving 47ms per encrypted order match at NIST Level 1 security.',
      pdfUrl: '/pdfs/lux-fhe-mpc-hybrid.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-mpc-hybrid.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['fhe', 'mpc', 'privacy', 'threshold'],
    },
    {
      id: 'fhe-smart-contracts',
      title: 'Fully Homomorphic Encryption for Smart Contract Execution',
      subtitle: 'Private DeFi with Encrypted Balances and Orderbooks',
      abstract: 'Architecture for executing smart contracts on fully homomorphic encrypted (FHE) data, enabling private DeFi where transaction amounts, balances, and orderbook entries are encrypted on-chain and manipulated without decryption. Uses Ring-LWE-based FHE with native Go and NTT SIMD acceleration.',
      pdfUrl: '/pdfs/lux-fhe-smart-contracts.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-smart-contracts.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'defi', 'evm'],
    },
    // ================================================================
    // Bridge & Cross-Chain
    // ================================================================
    {
      id: 'bridge',
      title: 'Lux Bridge',
      subtitle: 'Cross-Chain with ZK Light Clients & IBC Integration',
      abstract: 'Trustless cross-chain bridge using zero-knowledge light clients and IBC protocol for interoperability with Cosmos and Ethereum.',
      pdfUrl: '/pdfs/lux-bridge.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-bridge.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-07-01',
      authors: ['Lux Industries', 'Vishnu Seesahai'],
      tags: ['bridge', 'cross-chain', 'zk'],
    },
    {
      id: 'teleport-omnichain',
      title: 'Lux Teleport: Sovereign Omnichain Liquidity',
      subtitle: 'Non-Custodial Cross-Chain Asset Transfer via Threshold Cryptography',
      abstract: 'Non-custodial omnichain bridge connecting 20 execution environments and 270+ blockchains through unified MPC threshold signatures. Introduces sovereign per-chain governance, yield-bearing bridge tokens with 29 strategies, and Shariah-compliant DeFi mode.',
      pdfUrl: '/pdfs/lux-teleport-omnichain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-teleport-omnichain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2022-09-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['bridge', 'teleport', 'cross-chain', 'mpc', 'messaging'],
      relatedLinks: [
        { label: 'OmnichainRouter.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/OmnichainRouter.sol' },
        { label: 'ChainIds.sol (270 chains)', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/chains/ChainIds.sol' },
        { label: 'Formal Proofs', url: 'https://proofs.lux.network' },
      ],
    },
    {
      id: 'teleport-protocol',
      title: 'Lux Interchain Transfer Protocol (LITP)',
      subtitle: 'Trustless Token Transfers Between Appchains and External Blockchains',
      abstract: 'Trustless mechanism for transferring tokens between Lux Network appchains and external blockchains (Ethereum, Cosmos, Bitcoin). Intra-ecosystem transfers use Warp Messaging with BLS aggregate signatures achieving sub-second finality; cross-ecosystem transfers use light client verification. Benchmarks show Lux-to-Lux transfers in under 4 seconds.',
      pdfUrl: '/pdfs/lux-teleport-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-teleport-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['bridge', 'teleport', 'cross-chain', 'messaging'],
    },
    {
      id: 'teleport-architecture',
      title: 'Lux Teleport Engineering Architecture',
      subtitle: 'Four-Layer Universal Bridge for 270+ Chains from a Single Binary',
      abstract: 'Engineering architecture of Lux Teleport: frozen wire protocol with four canonical proof tags (DEPOSIT, YIELD, BACKING, RELEASE), chain-agnostic Teleporter contract, pluggable chain adapter layer supporting Lux-native, external EVM, Bitcoin-family script chains, and non-EVM account-model chains, plus multi-tenant white-label architecture.',
      pdfUrl: '/pdfs/lux-teleport-architecture.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-teleport-architecture.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['bridge', 'teleport', 'cross-chain', 'messaging'],
    },
    {
      id: 'teleport-protocol-spec',
      title: 'Teleport Protocol Specification',
      subtitle: 'Canonical Wire Format and Message Schema',
      abstract: 'Formal protocol specification for Lux Teleport defining the canonical wire format, message schema, proof verification, and chain adapter interfaces.',
      pdfUrl: '/pdfs/lux-teleport-protocol-spec.pdf',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['bridge', 'teleport', 'cross-chain', 'messaging'],
    },
    {
      id: 'secure-messaging',
      title: 'Authenticated Cross-Chain Message Protocol',
      subtitle: 'Eliminating the $2B Bridge Attack Surface',
      abstract: 'Authenticated cross-chain message protocol eliminating bridge failure modes responsible for over $2B in losses. Specifies a formal message envelope with 13 mandatory fields, five classes of replay protection, MPC threshold attestation, and eight mandatory verification checks on every receive path.',
      pdfUrl: '/pdfs/lux-secure-messaging.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-secure-messaging.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['bridge', 'cross-chain', 'messaging', 'security'],
    },
    {
      id: 'cross-chain-security',
      title: 'Cross-Chain Security Architecture',
      subtitle: 'Security of Multi-Chain Composition with Shared Validator Sets',
      abstract: 'Security architecture of multi-chain blockchain networks with shared validator sets. Identifies four classes of cross-chain attack: bridge exploits via message forgery, replay attacks across chain boundaries, finality mismatch exploitation, and validator set desynchronization. Proves triple-proof finality propagation ensures transaction finality across all chains within one epoch (1 second).',
      pdfUrl: '/pdfs/lux-cross-chain-security.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-cross-chain-security.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['bridge', 'cross-chain', 'security'],
    },
    {
      id: 'warp-messaging',
      title: 'Warp Messaging Protocol',
      subtitle: 'Native Cross-Chain Messaging',
      abstract: 'Native cross-chain messaging protocol for efficient inter-subnet communication on Lux Network.',
      pdfUrl: '/pdfs/lux-warp-messaging.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-warp-messaging.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['bridge', 'cross-chain', 'messaging'],
    },
    // ================================================================
    // Chain Implementations
    // ================================================================
    {
      id: 'achain',
      title: 'A-Chain: Attestation Chain',
      subtitle: 'TEE Attestation & AI Compute Verification',
      abstract: 'Trusted Execution Environment attestation chain supporting Intel SGX, AMD SEV-SNP, NVIDIA H100 CC, and ARM CCA for verifiable AI compute.',
      pdfUrl: '/pdfs/lux-achain-attestation.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-achain-attestation.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-10-01',
      authors: ['Lux Industries'],
      tags: ['security'],
    },
    {
      id: 'gchain',
      title: 'G-Chain: GraphQL Chain',
      subtitle: 'Universal GraphQL Query Engine with BadgerDB',
      abstract: 'High-performance query layer with GraphQL API and BadgerDB storage for efficient blockchain data access and indexing.',
      pdfUrl: '/pdfs/lux-gchain-graphql.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-gchain-graphql.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-01',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'mchain',
      title: 'M-Chain: MPC Chain',
      subtitle: 'MPC Threshold Custody (CGG21, MuSig2, FROST, Ringtail)',
      abstract: 'Multi-party computation chain for threshold custody supporting multiple protocols including post-quantum Ringtail signatures.',
      pdfUrl: '/pdfs/lux-mchain-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-mchain-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-15',
      authors: ['Lux Industries', 'Vishnu Seesahai'],
      tags: ['mpc', 'threshold', 'pq'],
    },
    {
      id: 'zchain',
      title: 'Z-Chain: Zero-Knowledge Chain',
      subtitle: 'Privacy-Preserving Smart Contracts (zkEVM, FHE, TEE)',
      abstract: 'Privacy layer combining zkEVM, fully homomorphic encryption, and trusted execution environments for confidential smart contracts.',
      pdfUrl: '/pdfs/lux-zchain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zchain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-11-01',
      authors: ['Lux Industries'],
      tags: ['privacy', 'fhe', 'zk'],
    },
    // ================================================================
    // Infrastructure & EVM
    // ================================================================
    {
      id: 'evm-precompiles',
      title: 'EVM Precompiles for Post-Quantum Cryptography',
      subtitle: 'Native Post-Quantum Operations in EVM',
      abstract: 'EVM precompiles enabling native post-quantum cryptographic operations for efficient on-chain verification.',
      pdfUrl: '/pdfs/lux-evm-precompiles.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-evm-precompiles.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['evm', 'precompile', 'pq'],
    },
    {
      id: 'gpu-evm-whitepaper',
      title: 'cevm: GPU-Native EVM with Post-Quantum and FHE Acceleration',
      subtitle: 'Full Block Processing Pipeline on GPU Hardware',
      abstract: 'cevm, a GPU-native Ethereum Virtual Machine that executes the entire block processing pipeline -- transaction validation, signature recovery, Block-STM parallel execution, opcode dispatch, and state root computation -- on GPU hardware.',
      pdfUrl: '/pdfs/gpu-evm-whitepaper.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/gpu-evm-whitepaper.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['evm', 'gpu'],
    },
    {
      id: 'evmgpu-benchmark',
      title: 'GPU-Accelerated EVM Execution: Measured Benchmarks',
      subtitle: '4.85x Peak Speedup on Apple M1 Max Metal GPU',
      abstract: 'Measured benchmarks of GPU-accelerated EVM execution on Apple M1 Max with 32-core Metal GPU and 64GB unified memory. GPU EVM kernel achieves 85.9M opcodes/sec versus 17.7M opcodes/sec on CPU -- a 4.85x peak speedup. Achieves 20.9 Ggas/s (best: 23.4 Ggas/s) -- 5.1x faster than Go EVM.',
      pdfUrl: '/pdfs/evmgpu-benchmark.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/evmgpu-benchmark.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['evm', 'gpu'],
    },
    {
      id: 'verkle',
      title: 'Verkle Trees',
      subtitle: 'Constant-Size Proofs (~150 bytes) for Stateless Clients',
      abstract: 'Implementation of Verkle trees for efficient state proofs enabling stateless client operation with minimal bandwidth.',
      pdfUrl: '/pdfs/lux-verkle-trees.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-verkle-trees.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-10-01',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'fraud-proofs',
      title: 'Fraud Proofs',
      subtitle: 'Optimistic Rollups with Interactive Bisection Game',
      abstract: 'Optimistic rollup implementation with efficient fraud proof mechanism using interactive bisection for dispute resolution.',
      pdfUrl: '/pdfs/lux-fraud-proofs.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fraud-proofs.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-11-15',
      authors: ['Lux Industries'],
      tags: ['evm', 'zk'],
    },
    {
      id: 'data-availability',
      title: 'Data Availability Layer',
      subtitle: 'Erasure Coding and KZG Commitments',
      abstract: 'Data availability layer using erasure coding and KZG commitments for scalable blockchain data guarantees.',
      pdfUrl: '/pdfs/lux-data-availability.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-data-availability.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'state-sync',
      title: 'State Synchronization Protocol',
      subtitle: 'Fast State Sync with Merkle Range Proofs',
      abstract: 'Fast state synchronization protocol using Merkle range proofs for efficient node bootstrapping.',
      pdfUrl: '/pdfs/lux-state-sync.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-state-sync.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'tee-mesh',
      title: 'TEE Computing Mesh',
      subtitle: 'Distributed TEE Network for Confidential Computing',
      abstract: 'Mesh network of trusted execution environments (SGX, SEV-SNP, TDX, CCA) for distributed confidential computing.',
      pdfUrl: '/pdfs/lux-tee-computing-mesh.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tee-computing-mesh.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-12-01',
      authors: ['Lux Industries'],
      tags: ['security', 'privacy'],
    },
    {
      id: 'reproducible-builds',
      title: 'Reproducible Builds and ML-DSA Signed Binaries',
      subtitle: 'Deterministic Builds with Hybrid BLS+ML-DSA Attestation Chain',
      abstract: 'Release pipeline enforcing deterministic builds, ML-DSA (FIPS 204) signed binaries, and an attestation chain from source commit to deployed container image. Every release artifact carries a hybrid BLS+ML-DSA signature over a content-addressed manifest. Reproducibility verified by independent rebuilders with attestations published to a transparency log anchored in Q-Chain.',
      pdfUrl: '/pdfs/lux-reproducible-builds.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-reproducible-builds.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['security', 'mldsa'],
    },
    // ================================================================
    // Wire Protocol & Networking
    // ================================================================
    {
      id: 'zap-wire-protocol',
      title: 'ZAP: Zero-Allocation Wire Protocol',
      subtitle: '20.26M TPS in Batch Mode, 8.7us Latency, PQ TLS 1.3',
      abstract: 'Zero-allocation binary wire protocol for inter-node consensus communication. Achieves 20.26 million TPS in batch mode and 376,000 TPS in parallel streaming with 8.7us per-message latency. Uses fixed-size message framing with TLV encoding, Ed25519 authentication, and optional PQ TLS 1.3 (X25519MLKEM768).',
      pdfUrl: '/pdfs/lux-zap-wire-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zap-wire-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['zap', 'pq'],
    },
    {
      id: 'zap-benchmarks',
      title: 'ZAP Performance Benchmarks',
      subtitle: 'vs gRPC, libp2p, JSON-RPC, Cap\'n Proto, FlatBuffers, QUIC',
      abstract: 'Comprehensive performance evaluation of ZAP against six competing protocols -- gRPC, libp2p, JSON-RPC, Cap\'n Proto, FlatBuffers, and QUIC -- across serialization throughput, round-trip latency, memory allocation, CPU utilization, concurrent connection scalability, and variable message size performance. ZAP achieves 4.2 million single-stream serializations per second with zero heap allocations.',
      pdfUrl: '/pdfs/lux-zap-benchmarks.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zap-benchmarks.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['zap'],
    },
    // ================================================================
    // DeFi
    // ================================================================
    {
      id: 'lightspeed-dex',
      title: 'Lightspeed DEX',
      subtitle: 'HFT-Optimized DEX with 261ms Latency & FPGA Matching',
      abstract: 'Ultra-low latency decentralized exchange with FPGA-accelerated order matching achieving institutional-grade performance.',
      pdfUrl: '/pdfs/lux-lightspeed-dex.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-lightspeed-dex.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-05-01',
      authors: ['Lux Industries'],
      tags: ['defi', 'dex'],
    },
    {
      id: 'credit',
      title: 'Lux Credit',
      subtitle: 'Self-Repaying Lending with 90% LTV & 11% APY',
      abstract: 'Novel lending protocol with self-repaying mechanism, high loan-to-value ratios, and attractive yields on LUX staking.',
      pdfUrl: '/pdfs/lux-credit-lending.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-credit-lending.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-15',
      authors: ['Lux Industries'],
      tags: ['defi', 'lending'],
    },
    {
      id: 'credit-protocol-spec',
      title: 'Lux Credit Protocol Specification',
      subtitle: 'Canonical Spec for Omnichain Collateralized Credit Issuance',
      abstract: 'Canonical specification for the Lux Credit Protocol, an omnichain system for collateralized credit issuance, cross-chain transport, and atomic settlement. Issues overcollateralized, in-kind redeemable credit tokens subject to hard loan-to-value constraints. Decomposes into four auditable subsystems: collateral custody, credit issuance, transport/finality, and surplus allocation.',
      pdfUrl: '/pdfs/lux-credit-protocol-spec.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-credit-protocol-spec.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['defi', 'lending'],
    },
    {
      id: 'perpetuals',
      title: 'Perpetuals & Derivatives',
      subtitle: 'GMX2 Integration with Funding Rates & Liquidation Engine',
      abstract: 'Perpetual futures and derivatives platform integrated with GMX v2 architecture for advanced trading capabilities.',
      pdfUrl: '/pdfs/lux-perpetuals-derivatives.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-perpetuals-derivatives.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-10-15',
      authors: ['Lux Industries'],
      tags: ['defi', 'dex'],
    },
    {
      id: 'liquid-staking',
      title: 'Liquid Staking Protocol',
      subtitle: 'Staked LUX Derivatives with DeFi Composability',
      abstract: 'Liquid staking protocol for LUX with DeFi-composable staked derivatives.',
      pdfUrl: '/pdfs/lux-liquid-staking.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-liquid-staking.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    {
      id: 'restaking',
      title: 'Restaking Protocol',
      subtitle: 'Shared Security via Validator Restaking',
      abstract: 'Restaking protocol enabling shared security through validator restaking across multiple networks.',
      pdfUrl: '/pdfs/lux-restaking.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-restaking.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    {
      id: 'omnichain-yield',
      title: 'Yield-Bearing Bridge Tokens',
      subtitle: 'Cross-Chain Capital Efficiency through Composable Yield Strategies',
      abstract: '$15B+ locked in bridges earning zero yield. Yield-bearing bridge tokens (yLETH, yLBTC, yLUSD) deploy locked assets to 29 strategies across 9 categories. Share-price monotonicity proof, auto-pause on undercollateralization, xLUX flywheel economics.',
      pdfUrl: '/pdfs/lux-omnichain-yield.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-omnichain-yield.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-12-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['defi', 'yield', 'bridge'],
      relatedLinks: [
        { label: 'YieldBearingBridgeToken.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/yield/YieldBearingBridgeToken.sol' },
        { label: '29 Yield Strategies', url: 'https://github.com/luxfi/standard/tree/main/contracts/bridge/yield/strategies' },
        { label: 'LiquidLUX (xLUX)', url: 'https://github.com/luxfi/standard/blob/main/contracts/liquid/LiquidLUX.sol' },
      ],
    },
    {
      id: 'sovereign-defi',
      title: 'Sovereign DeFi',
      subtitle: 'Per-Chain Governance, Shariah Compliance, and Securities Infrastructure',
      abstract: 'Sovereign governance model where each chain controls its own bridge economics. Governance isolation theorem (governor cannot mint). First protocol-level Shariah compliance for DeFi (ShariaFilter contract, SAB multisig). ERC-3643 securities compliance with settlement registry.',
      pdfUrl: '/pdfs/lux-sovereign-defi.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-sovereign-defi.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2022-01-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['defi', 'governance'],
      relatedLinks: [
        { label: 'OmnichainRouter.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/OmnichainRouter.sol' },
        { label: 'ShariaFilter.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/yield/ShariaFilter.sol' },
        { label: 'Formal Proofs', url: 'https://proofs.lux.network' },
      ],
    },
    {
      id: 'oracle',
      title: 'Oracle Infrastructure',
      subtitle: 'AI Oracle (LP-106) + Traditional Price Feeds',
      abstract: 'Hybrid oracle system combining AI-powered LP-106 protocol with Chainlink and Pyth for reliable price feeds.',
      pdfUrl: '/pdfs/lux-oracle-infrastructure.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-oracle-infrastructure.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-01',
      authors: ['Lux Industries'],
      tags: ['defi'],
    },
    {
      id: 'market',
      title: 'Lux.market NFT',
      subtitle: 'NFT Marketplace with Reservoir Aggregation',
      abstract: 'Multi-chain NFT marketplace aggregating liquidity from 14+ chains using Reservoir protocol for optimal pricing.',
      pdfUrl: '/pdfs/lux-market-nft.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-market-nft.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-07-15',
      authors: ['Lux Industries'],
      tags: ['defi'],
    },
    // ================================================================
    // Privacy
    // ================================================================
    {
      id: 'privacy-pool',
      title: 'Privacy Pool Protocol',
      subtitle: 'Compliant Privacy with Selective Disclosure',
      abstract: 'Privacy pool protocol combining compliant privacy with selective disclosure using zero-knowledge proofs.',
      pdfUrl: '/pdfs/lux-privacy-pool.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-privacy-pool.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['privacy', 'zk'],
    },
    // ================================================================
    // Identity & Governance
    // ================================================================
    {
      id: 'id-iam',
      title: 'Lux ID IAM',
      subtitle: 'Identity & Access Management',
      abstract: 'Enterprise-grade identity and access management supporting OAuth 2.0, OIDC, SAML, WebAuthn, and multi-factor authentication.',
      pdfUrl: '/pdfs/lux-id-iam.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-iam.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-06-15',
      authors: ['Lux Industries'],
      tags: ['did', 'iam'],
    },
    {
      id: 'id-did',
      title: 'Lux ID DID Specification',
      subtitle: 'Decentralized Identifiers (did:lux:)',
      abstract: 'W3C-compliant DID specification for Lux Network enabling self-sovereign identity and verifiable credentials.',
      pdfUrl: '/pdfs/lux-id-did-specification.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-did-specification.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-06-20',
      authors: ['Lux Industries'],
      tags: ['did', 'iam'],
    },
    {
      id: 'governance',
      title: 'Governance & DAO',
      subtitle: 'Multi-Ecosystem DAO (Lux, Zoo, Hanzo)',
      abstract: 'Holographic consensus-based governance spanning Lux, Zoo, and Hanzo ecosystems for unified decision-making.',
      pdfUrl: '/pdfs/lux-governance-dao.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-governance-dao.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-01',
      authors: ['Lux Industries'],
      tags: ['governance'],
    },
    {
      id: 'dao-framework',
      title: 'DAO Governance Framework',
      subtitle: 'Azorius Framework with ERC6551 NFT Governance',
      abstract: 'Advanced DAO governance using Azorius framework with ERC6551 token-bound accounts for NFT-based voting.',
      pdfUrl: '/pdfs/lux-dao-governance-framework.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-dao-governance-framework.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-15',
      authors: ['Lux Industries'],
      tags: ['governance'],
    },
    // ================================================================
    // Economics
    // ================================================================
    {
      id: 'economics',
      title: 'Lux Network Economics',
      subtitle: 'Appchain Economic Models and Fee Structures',
      abstract: 'Economic models and fee structures for Lux Network appchains and the broader ecosystem.',
      pdfUrl: '/pdfs/lux-economics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-economics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['defi'],
    },
    {
      id: 'tokenomics',
      title: 'LUX Tokenomics',
      subtitle: 'Token Distribution, Emission, and Governance',
      abstract: 'LUX token distribution, emission schedule, and governance mechanisms for the Lux Network.',
      pdfUrl: '/pdfs/lux-tokenomics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tokenomics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    {
      id: 'validator-economics',
      title: 'Validator Economics',
      subtitle: 'Staking Rewards, Slashing, and Economic Security',
      abstract: 'Validator economics covering staking rewards, slashing conditions, and economic security guarantees.',
      pdfUrl: '/pdfs/lux-validator-economics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-validator-economics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    // ================================================================
    // Security
    // ================================================================
    {
      id: 'master-security-model',
      title: 'Comprehensive Security Model for the Lux Network',
      subtitle: 'Four Adversary Classes, Four Protocol Layers, Three Assumption Families',
      abstract: 'Comprehensive, layered security model making every security assumption explicit, every failure mode enumerated, and every trust boundary documented. Covers four adversary classes (classical, quantum, economic, network-level), four protocol layers (consensus, transport, execution, application), and three cryptographic assumption families.',
      pdfUrl: '/pdfs/lux-master-security-model.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-master-security-model.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['security'],
    },
    {
      id: 'hsm-boundary',
      title: 'HSM Boundary Design for Validator Key Infrastructure',
      subtitle: 'Hardware Security Modules + Threshold Cryptography Defense-in-Depth',
      abstract: 'Analysis of HSM and TEE boundary design for Lux validator key infrastructure. Specifies key material locality, side-channel assumptions for BLS and ML-DSA, attestation models for TEE-hosted signers, and interaction between HSM-enforced access policies and threshold signature protocols (FROST for BLS, Ringtail for post-quantum).',
      pdfUrl: '/pdfs/lux-hsm-boundary.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-hsm-boundary.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['security', 'threshold', 'mpc'],
    },
    {
      id: 'zero-trust-validators',
      title: 'Zero-Trust Validator Architecture',
      subtitle: 'Cryptographic Workload Identity for Every Service Interaction',
      abstract: 'Zero-trust validator architecture where every service interaction -- signing requests, key access, peer connections, RPC calls -- is authenticated via cryptographic workload identity, authorized by policy, and continuously verified. No component trusts another based on network adjacency. SPIFFE-compatible workload identifiers bound to Q-Chain NodeIDs.',
      pdfUrl: '/pdfs/lux-zero-trust-validators.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zero-trust-validators.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['security'],
    },
    {
      id: 'performance-security-tradeoffs',
      title: 'Performance-Security Tradeoffs in the Lux Network',
      subtitle: 'Measured Cost of Every Cryptographic Primitive',
      abstract: 'Quantifies the performance cost of every cryptographic primitive: MPC threshold signing (50ms at 2-of-3 to 1.2s at 20-of-50), FHE bootstrapping (12ms per gate), BLS aggregation (O(1) verification), ML-DSA signatures (3,309 bytes, 51.7x ECDSA), STARK aggregation (O(log N) verification), and triple-proof epoch finality (248 bytes, 357us).',
      pdfUrl: '/pdfs/lux-performance-security-tradeoffs.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-performance-security-tradeoffs.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['security', 'pq', 'fhe', 'mpc'],
    },
    {
      id: 'proof-methodology',
      title: 'Proof Methodology and Verification Tiers',
      subtitle: 'Lean4, Halmos, Tamarin, TLA+, Forge for Every Protocol Component',
      abstract: 'Specifies Lux Network\'s proof obligations: what must be mechanically proved (Lean4), symbolically verified (Halmos, Tamarin), fuzzed (Forge, go-fuzz), model-checked (TLA+), and adversarially reviewed. Defines five verification tiers and assigns every protocol component to a tier.',
      pdfUrl: '/pdfs/lux-proof-methodology.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-proof-methodology.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['security', 'audit'],
    },
    // ================================================================
    // Roadmap & Adoption
    // ================================================================
    {
      id: 'adoption-roadmap',
      title: 'Lux Adoption Roadmap',
      subtitle: 'Phased Deployment from Classical BLS to Full Quasar Triple-Proof',
      abstract: 'Phased deployment plan for Lux Network\'s post-quantum and FHE infrastructure, from current production state (classical BLS consensus with PQ-ready architecture) to full Quasar triple-proof finality with confidential computing. Four deployment phases with explicit dependencies, migration checkpoints, compatibility layers, audit milestones, and operator education requirements.',
      pdfUrl: '/pdfs/lux-adoption-roadmap.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-adoption-roadmap.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026-04-01',
      authors: ['Lux Industries'],
      tags: ['pq', 'consensus', 'fhe'],
    },
    // ================================================================
    // Cover Page
    // ================================================================
    {
      id: 'cover',
      title: 'Lux Network',
      subtitle: 'Multi-Consensus Blockchain with Post-Quantum Cryptography',
      abstract: 'Cover page for the Lux Network research paper collection.',
      pdfUrl: '/pdfs/cover-lux.pdf',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-01-01',
      authors: ['Zach Kelling', 'Lux Industries'],
      tags: [],
    },
  ],
}
