export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Lux',
  fullName: 'Lux Network',
  description: 'Post-quantum secure, high-performance blockchain infrastructure - Layer-0 for Hanzo (AI Compute) and Zoo (AI/ML Specialization)',
  website: 'https://lux.network',
  github: 'https://github.com/luxfi',
  primaryColor: '#3498DB',
  secondaryColor: '#2980B9',
  accentColor: '#E67E22',
  logo: '/logos/lux-logo.svg',
  papers: [
    // ================================================================
    // Consensus Protocols
    // ================================================================
    {
      id: 'consensus',
      title: 'Lux Consensus: Physics-Inspired Metastable Blockchain Consensus',
      subtitle: 'Novel consensus mechanism using physics-inspired metastable dynamics for high-throughput finality',
      abstract: '',
      pdfUrl: '/pdfs/lux-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'quantum-consensus',
      title: 'Lux Quantum Consensus: Post-Quantum Secure Multi-Consensus Architecture',
      subtitle: 'Post-quantum cryptography with Dilithium signatures for validator consensus',
      abstract: '',
      pdfUrl: '/pdfs/lux-quantum-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quantum-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'pq', 'mldsa'],
    },
    {
      id: 'quasar-consensus',
      title: 'Quasar: Quantum-Secure Multi-Engine Consensus with Triple-Proof Quantum Finality',
      subtitle: 'Dual-certificate quantum-secure finality combining BLS and Ringtail signatures',
      abstract: '',
      pdfUrl: '/pdfs/lux-quasar-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quasar-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'quasar', 'pq', 'bls', 'finality'],
    },
    {
      id: 'fpc-consensus',
      title: 'Fast Probabilistic Consensus: Adaptive Threshold Consensus with Phase-Shift Dynamics',
      subtitle: 'High-throughput probabilistic consensus with adaptive security thresholds and sub-second finality',
      abstract: '',
      pdfUrl: '/pdfs/lux-fpc-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fpc-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'triple-proof-consensus',
      title: 'Triple-Proof Quantum Finality',
      subtitle: 'BLS + STARK-aggregated ML-DSA + Ringtail in 248 bytes per epoch',
      abstract: '',
      pdfUrl: '/pdfs/lux-triple-proof-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-triple-proof-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'pq', 'bls', 'mldsa', 'finality', 'zk'],
    },
    {
      id: 'quasar-benchmarks',
      title: 'Quasar Consensus: A Comparative Benchmark Study of Post-Quantum Byzantine Fault Tolerance',
      subtitle: 'Post-quantum BFT vs Tendermint, HotStuff, Narwhal, Ethereum PoS, Solana, Avalanche',
      abstract: '',
      pdfUrl: '/pdfs/lux-quasar-benchmarks.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quasar-benchmarks.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'quasar', 'pq', 'finality'],
    },
    {
      id: 'field-protocol',
      title: 'Field Protocol: Electromagnetic-Inspired Distributed Consensus',
      subtitle: 'Validator preferences as dipoles in a vector field',
      abstract: '',
      pdfUrl: '/pdfs/lux-field-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-field-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'flare-protocol',
      title: 'Flare Protocol: Certificate Skip Exclusivity with Honest Support in DAG Consensus',
      subtitle: 'Conviction-based consensus in DAG structures',
      abstract: '',
      pdfUrl: '/pdfs/lux-flare-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-flare-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'nebula-protocol',
      title: 'Nebula Protocol: Probabilistic Finality in Sparse Networks',
      subtitle: 'Consensus for sparse validator networks with partial reachability',
      abstract: '',
      pdfUrl: '/pdfs/lux-nebula-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-nebula-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'nova-protocol',
      title: 'Nova Protocol: Supernova Burst Consensus for High-Throughput DAG Chains',
      subtitle: 'High throughput via simultaneous DAG vertex finalization',
      abstract: '',
      pdfUrl: '/pdfs/lux-nova-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-nova-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'photon-protocol',
      title: 'Photon Protocol: Zero-Latency Consensus Pipelining',
      subtitle: 'Overlapping sampling rounds for multiple transactions',
      abstract: '',
      pdfUrl: '/pdfs/lux-photon-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-photon-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'prism-protocol',
      title: 'Prism Protocol: Multi-Spectrum Parallel Consensus',
      subtitle: 'Independent frequency bands for concurrent transaction processing',
      abstract: '',
      pdfUrl: '/pdfs/lux-prism-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-prism-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'ray-protocol',
      title: 'Ray Protocol: Adaptive Finality with Light-Speed Confirmation',
      subtitle: 'Dynamic parameter adjustment based on network conditions',
      abstract: '',
      pdfUrl: '/pdfs/lux-ray-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ray-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    {
      id: 'wave-protocol',
      title: 'Wave Protocol: Decision Stability and Confidence Monotonicity in DAG-Based Metastable Consensus',
      subtitle: 'Persistent confidence counters in DAG-based transaction structures',
      abstract: '',
      pdfUrl: '/pdfs/lux-wave-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-wave-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['consensus', 'finality'],
    },
    // ================================================================
    // Cryptography & Post-Quantum
    // ================================================================
    {
      id: 'ntt-transform',
      title: 'NTT Transform: Enabling Post-Quantum Cryptography on EVM with 85% Gas Reduction',
      subtitle: 'Number Theoretic Transform optimization for FALCON, Dilithium, STARKs on EVM',
      abstract: '',
      pdfUrl: '/pdfs/lux-ntt-transform.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ntt-transform.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'evm', 'precompile'],
    },
    {
      id: 'ntt-simd-implementation',
      title: 'Number Theoretic Transform with SIMD Acceleration',
      subtitle: 'Hardware-accelerated polynomial multiplication for lattice cryptography',
      abstract: '',
      pdfUrl: '/pdfs/lux-ntt-simd-implementation.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ntt-simd-implementation.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'lattice'],
    },
    {
      id: 'ethfalcon-post-quantum',
      title: 'ETHFALCON: EVM-Optimized Post-Quantum Signatures',
      subtitle: 'Optimized FALCON post-quantum signatures for Ethereum',
      abstract: '',
      pdfUrl: '/pdfs/lux-ethfalcon-post-quantum.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ethfalcon-post-quantum.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'lattice'],
    },
    {
      id: 'ringtail-pq',
      title: 'Ringtail: Lattice-Based Post-Quantum Threshold Signatures for Blockchain Consensus',
      subtitle: 't-of-n validators sign without full secret key reconstruction',
      abstract: '',
      pdfUrl: '/pdfs/lux-ringtail-pq.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ringtail-pq.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'lattice', 'threshold', 'mpc'],
    },
    {
      id: 'pq-crypto-suite',
      title: 'Post-Quantum Cryptographic Suite for EVM: ML-KEM, ML-DSA, and SLH-DSA as Native Precompiles',
      subtitle: 'FIPS 203/204/205 at 50K-150K gas as native EVM precompiles',
      abstract: '',
      pdfUrl: '/pdfs/lux-pq-crypto-suite.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-pq-crypto-suite.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'mldsa', 'evm', 'precompile', 'lattice'],
    },
    {
      id: 'pq-migration',
      title: 'Post-Quantum Migration Strategy for Production Blockchain Networks',
      subtitle: 'Three-phase transition from classical to post-quantum cryptography',
      abstract: '',
      pdfUrl: '/pdfs/lux-pq-migration.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-pq-migration.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'mldsa', 'bls', 'security'],
    },
    {
      id: 'hybrid-pq-architecture',
      title: 'Hybrid Post-Quantum Cryptographic Architecture for Blockchain Systems',
      subtitle: 'BLS12-381 + ML-DSA via dual-signature and key-combiner constructions',
      abstract: '',
      pdfUrl: '/pdfs/lux-hybrid-pq-architecture.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-hybrid-pq-architecture.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'bls', 'mldsa', 'lattice'],
    },
    {
      id: 'hybrid-certificates',
      title: 'Hybrid Certificate Chains and Post-Quantum Trust Anchors for Validator Networks',
      subtitle: 'Dual ECDSA/BLS + ML-DSA signatures in a single certificate chain',
      abstract: '',
      pdfUrl: '/pdfs/lux-hybrid-certificates.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-hybrid-certificates.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'mldsa', 'security'],
    },
    {
      id: 'lattice-cryptography-primer',
      title: 'Lattice Cryptography from First Principles: A Builder\'s Guide',
      subtitle: 'Practical introduction to lattice-based cryptography for blockchain engineers',
      abstract: '',
      pdfUrl: '/pdfs/lux-lattice-cryptography-primer.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-lattice-cryptography-primer.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'lattice'],
    },
    {
      id: 'crypto-agility',
      title: 'Cryptographic Agility Architecture for Long-Lived Blockchain Systems',
      subtitle: 'Live rotation of signature schemes and hash functions without chain halts',
      abstract: '',
      pdfUrl: '/pdfs/lux-crypto-agility.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-crypto-agility.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'security'],
    },
    {
      id: 'quantum-threat-blockchain',
      title: 'Quantum Threat Model for Blockchain Infrastructure',
      subtitle: 'Full attack surface beyond signature forgery',
      abstract: '',
      pdfUrl: '/pdfs/lux-quantum-threat-blockchain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quantum-threat-blockchain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'security'],
    },
    // ================================================================
    // Threshold Signatures & MPC
    // ================================================================
    {
      id: 'universal-threshold-signatures',
      title: 'Universal Threshold Signatures: Multi-Chain Cryptographic Infrastructure with Post-Quantum Security',
      subtitle: 'Unified framework (CMP, FROST, LSS, Doerner, Ringtail)',
      abstract: '',
      pdfUrl: '/pdfs/lux-universal-threshold-signatures.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-universal-threshold-signatures.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['threshold', 'mpc', 'pq'],
    },
    {
      id: 'threshold-mpc',
      title: 'Unified Threshold Cryptography for Omnichain Asset Custody: FROST, CGGMP21, and Taproot Integration',
      subtitle: 'FROST + CGGMP21 + Taproot for 20 chain families',
      abstract: '',
      pdfUrl: '/pdfs/lux-threshold-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-threshold-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['threshold', 'mpc', 'pq'],
      relatedLinks: [
        { label: 'luxfi/threshold (Go)', url: 'https://github.com/luxfi/threshold' },
        { label: 'luxfi/mpc (Go)', url: 'https://github.com/luxfi/mpc' },
        { label: 'FROST Precompile', url: 'https://github.com/luxfi/standard/tree/main/src/precompiles/frost' },
      ],
    },
    {
      id: 'lss-mpc',
      title: 'LSS: Linear Shamir\'s Secret Sharing --- A Pragmatic Framework for Dynamic and Resilient Threshold Signatures with Live Secret Resharing',
      subtitle: 'Dynamic threshold signatures with live secret resharing',
      abstract: '',
      pdfUrl: '/pdfs/lux-lss-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-lss-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['threshold', 'mpc', 'pq'],
      relatedLinks: [
        { label: 'luxfi/threshold (Go)', url: 'https://github.com/luxfi/threshold' },
        { label: 'luxfi/mpc (Go)', url: 'https://github.com/luxfi/mpc' },
      ],
    },
    {
      id: 'validator-mpc',
      title: 'Threshold Cryptography for Validator Networks',
      subtitle: 'CGGMP21 + FROST + Ringtail for validator signing',
      abstract: '',
      pdfUrl: '/pdfs/lux-validator-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-validator-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['threshold', 'mpc', 'pq'],
    },
    // ================================================================
    // FHE (Fully Homomorphic Encryption)
    // ================================================================
    {
      id: 'tfhe',
      title: 'Torus Threshold Fully Homomorphic Encryption: Boolean Circuits on Encrypted Data with Distributed Decryption',
      subtitle: 'Threshold TFHE for t-of-n distributed decryption',
      abstract: '',
      pdfUrl: '/pdfs/lux-tfhe.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tfhe.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'lattice', 'threshold'],
    },
    {
      id: 'fhe-api',
      title: 'FHE API and Developer Model for Practical Private Applications',
      subtitle: 'Go API for lattice-based FHE with SIMD-optimized NTT',
      abstract: '',
      pdfUrl: '/pdfs/lux-fhe-api.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-api.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'lattice'],
    },
    {
      id: 'fhe-benchmarks',
      title: 'FHE Benchmarking, Cost Models, and Operational SLOs',
      subtitle: '2.1M polynomial multiplications/sec, 12ms boolean AND with bootstrapping',
      abstract: '',
      pdfUrl: '/pdfs/lux-fhe-benchmarks.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-benchmarks.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'lattice'],
    },
    {
      id: 'fhe-mpc-hybrid',
      title: 'FHE + MPC Hybrid Systems for Trustless Private Computation',
      subtitle: 'Trustless private computation via TFHE + FROST threshold decryption',
      abstract: '',
      pdfUrl: '/pdfs/lux-fhe-mpc-hybrid.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-mpc-hybrid.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['fhe', 'mpc', 'privacy', 'threshold'],
    },
    {
      id: 'fhe-smart-contracts',
      title: 'Fully Homomorphic Encryption for Smart Contract Execution',
      subtitle: 'Private DeFi with encrypted balances and orderbooks',
      abstract: '',
      pdfUrl: '/pdfs/lux-fhe-smart-contracts.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fhe-smart-contracts.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['fhe', 'privacy', 'defi', 'evm'],
    },
    // ================================================================
    // Bridge & Cross-Chain
    // ================================================================
    {
      id: 'bridge',
      title: 'Lux Bridge: Threshold-Secured Cross-Chain Communication with MPC Custody, Post-Quantum Verification, and Formally Verified Contract Invariants',
      subtitle: 'Cross-chain with ZK light clients and IBC integration',
      abstract: '',
      pdfUrl: '/pdfs/lux-bridge.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-bridge.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'cross-chain', 'zk', 'mpc', 'pq'],
    },
    {
      id: 'teleport-omnichain',
      title: 'Lux Teleport: Sovereign Omnichain Liquidity via Threshold Cryptography and Per-Chain Governance',
      subtitle: 'Non-custodial cross-chain asset transfer via threshold cryptography',
      abstract: '',
      pdfUrl: '/pdfs/lux-teleport-omnichain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-teleport-omnichain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'teleport', 'cross-chain', 'mpc', 'messaging'],
      relatedLinks: [
        { label: 'OmnichainRouter.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/OmnichainRouter.sol' },
        { label: 'ChainIds.sol (270 chains)', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/chains/ChainIds.sol' },
      ],
    },
    {
      id: 'teleport-protocol',
      title: 'Teleport Protocol: Trustless Cross-Chain Asset Transfer via Light Client Verification',
      subtitle: 'Trustless token transfers between appchains and external blockchains',
      abstract: '',
      pdfUrl: '/pdfs/lux-teleport-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-teleport-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'teleport', 'cross-chain', 'messaging'],
    },
    {
      id: 'teleport-architecture',
      title: 'Teleport Universal Bridge Architecture: Frozen Wire Format, Pluggable Chain Adapters, and Multi-Tenant Deployment',
      subtitle: 'Four-layer universal bridge for 270+ chains from a single binary',
      abstract: '',
      pdfUrl: '/pdfs/lux-teleport-architecture.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-teleport-architecture.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'teleport', 'cross-chain', 'messaging'],
    },
    {
      id: 'teleport-protocol-spec',
      title: 'Teleport Protocol Specification',
      subtitle: 'Canonical wire format and message schema',
      abstract: '',
      pdfUrl: '/pdfs/lux-teleport-protocol-spec.pdf',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'teleport', 'cross-chain', 'messaging'],
    },
    {
      id: 'secure-messaging',
      title: 'Authenticated Cross-Chain Message Protocol',
      subtitle: 'Eliminating the $2B bridge attack surface',
      abstract: '',
      pdfUrl: '/pdfs/lux-secure-messaging.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-secure-messaging.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'cross-chain', 'messaging', 'security'],
    },
    {
      id: 'cross-chain-security',
      title: 'Security Architecture for Multi-Chain Networks',
      subtitle: 'Security of multi-chain composition with shared validator sets',
      abstract: '',
      pdfUrl: '/pdfs/lux-cross-chain-security.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-cross-chain-security.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'cross-chain', 'security'],
    },
    {
      id: 'warp-messaging',
      title: 'Lux Warp Messaging: Cross-Appchain Communication with BLS Aggregate Signatures',
      subtitle: 'Native cross-chain messaging for inter-subnet communication',
      abstract: '',
      pdfUrl: '/pdfs/lux-warp-messaging.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-warp-messaging.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['bridge', 'cross-chain', 'messaging', 'bls'],
    },
    // ================================================================
    // Chain Implementations
    // ================================================================
    {
      id: 'achain-attestation',
      title: 'A-Chain: Unified Trusted Execution Environment Attestation for Decentralized AI Compute',
      subtitle: 'TEE attestation for Intel SGX, AMD SEV-SNP, NVIDIA H100 CC, and ARM CCA',
      abstract: '',
      pdfUrl: '/pdfs/lux-achain-attestation.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-achain-attestation.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security'],
    },
    {
      id: 'gchain-graphql',
      title: 'G-Chain: Unified GraphQL Query Engine with Decentralized Indexing for Multi-Chain State',
      subtitle: 'Universal GraphQL query engine with BadgerDB storage',
      abstract: '',
      pdfUrl: '/pdfs/lux-gchain-graphql.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-gchain-graphql.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'mchain-mpc',
      title: 'M-Chain: Decentralized Multi-Party Computation Custody with Quantum-Safe Threshold Signatures',
      subtitle: 'MPC threshold custody (CGG21, MuSig2, FROST, Ringtail)',
      abstract: '',
      pdfUrl: '/pdfs/lux-mchain-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-mchain-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['mpc', 'threshold', 'pq'],
    },
    {
      id: 'zchain',
      title: 'Lux Z-Chain: Privacy-Preserving Smart Contracts with Zero-Knowledge Proofs',
      subtitle: 'Privacy-preserving smart contracts (zkEVM, FHE, TEE)',
      abstract: '',
      pdfUrl: '/pdfs/lux-zchain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zchain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['privacy', 'fhe', 'zk'],
    },
    {
      id: 'capsule-architecture',
      title: 'The Capsule: A Sovereign Encrypted Process for Web5 Computing',
      subtitle: 'Sovereign encrypted compute process for decentralized applications',
      abstract: '',
      pdfUrl: '/pdfs/lux-capsule-architecture.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-capsule-architecture.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['privacy', 'security'],
    },
    // ================================================================
    // Infrastructure & EVM
    // ================================================================
    {
      id: 'evm-precompiles',
      title: 'Custom EVM Precompiles for Cryptographic Operations on Lux Network',
      subtitle: 'Native post-quantum operations in the EVM',
      abstract: '',
      pdfUrl: '/pdfs/lux-evm-precompiles.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-evm-precompiles.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm', 'precompile', 'pq'],
    },
    {
      id: 'evm-precompile-engineering',
      title: 'Engineering EVM Precompiles for Cryptographic Primitives',
      subtitle: 'Implementation patterns for high-performance EVM precompiled contracts',
      abstract: '',
      pdfUrl: '/pdfs/lux-evm-precompile-engineering.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-evm-precompile-engineering.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm', 'precompile'],
    },
    {
      id: 'gpu-evm-whitepaper',
      title: 'cevm: A GPU-Native Ethereum Virtual Machine with Post-Quantum Cryptography and FHE Acceleration',
      subtitle: 'Full block processing pipeline on GPU hardware',
      abstract: '',
      pdfUrl: '/pdfs/gpu-evm-whitepaper.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/gpu-evm-whitepaper.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm', 'gpu'],
    },
    {
      id: 'evmgpu-benchmark',
      title: 'GPU-Accelerated EVM Execution: Measured Benchmarks on Apple M1 Max Metal',
      subtitle: '4.85x peak speedup on Apple M1 Max Metal GPU',
      abstract: '',
      pdfUrl: '/pdfs/evmgpu-benchmark.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/evmgpu-benchmark.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm', 'gpu'],
    },
    {
      id: 'verkle-trees',
      title: 'Verkle Trees: Constant-Size Proofs for Stateless Clients on Lux',
      subtitle: 'Constant-size proofs (~150 bytes) for stateless clients',
      abstract: '',
      pdfUrl: '/pdfs/lux-verkle-trees.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-verkle-trees.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'fraud-proofs',
      title: 'Fraud Proofs: Optimistic Rollup Security on Lux with Interactive Verification',
      subtitle: 'Optimistic rollups with interactive bisection game',
      abstract: '',
      pdfUrl: '/pdfs/lux-fraud-proofs.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fraud-proofs.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm', 'zk'],
    },
    {
      id: 'data-availability',
      title: 'Data Availability Sampling in Lux Network',
      subtitle: 'Erasure coding and KZG commitments for scalable data guarantees',
      abstract: '',
      pdfUrl: '/pdfs/lux-data-availability.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-data-availability.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'state-sync',
      title: 'Fast State Synchronization for Blockchain Nodes via Merkle Range Proofs',
      subtitle: 'Fast state sync with Merkle range proofs for efficient node bootstrapping',
      abstract: '',
      pdfUrl: '/pdfs/lux-state-sync.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-state-sync.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['evm'],
    },
    {
      id: 'tee-computing-mesh',
      title: 'Lux TEE Mesh: Decentralized Confidential Computing Infrastructure for Blockchain Networks',
      subtitle: 'Distributed TEE network for confidential computing (SGX, SEV-SNP, TDX, CCA)',
      abstract: '',
      pdfUrl: '/pdfs/lux-tee-computing-mesh.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tee-computing-mesh.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security', 'privacy'],
    },
    {
      id: 'reproducible-builds',
      title: 'Signed Software, Reproducible Builds, and Quantum-Resilient Release Pipelines',
      subtitle: 'Deterministic builds with hybrid BLS+ML-DSA attestation chain',
      abstract: '',
      pdfUrl: '/pdfs/lux-reproducible-builds.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-reproducible-builds.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security', 'mldsa'],
    },
    // ================================================================
    // Wire Protocol & Networking
    // ================================================================
    {
      id: 'zap-wire-protocol',
      title: 'ZAP: Zero-Allocation Binary Wire Protocol for Consensus Transport',
      subtitle: '20.26M TPS in batch mode, 8.7us latency, PQ TLS 1.3',
      abstract: '',
      pdfUrl: '/pdfs/lux-zap-wire-protocol.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zap-wire-protocol.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['zap', 'pq'],
    },
    {
      id: 'zap-benchmarks',
      title: 'ZAP Benchmarks: Zero-Allocation Protocol Performance Analysis for Consensus Transport',
      subtitle: 'vs gRPC, libp2p, JSON-RPC, Cap\'n Proto, FlatBuffers, QUIC',
      abstract: '',
      pdfUrl: '/pdfs/lux-zap-benchmarks.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zap-benchmarks.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['zap'],
    },
    // ================================================================
    // DeFi
    // ================================================================
    {
      id: 'lightspeed-dex',
      title: 'Lux Lightspeed DEX: High-Frequency Trading at the Speed of Light',
      subtitle: 'HFT-optimized DEX with 261ms latency and FPGA matching',
      abstract: '',
      pdfUrl: '/pdfs/lux-lightspeed-dex.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-lightspeed-dex.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'dex'],
    },
    {
      id: 'credit-lending',
      title: 'Lux Credit: Zero-Interest Self-Repaying Lending Protocol with 90% LTV and Cross-Chain Collateral',
      subtitle: 'Self-repaying lending with 90% LTV and 11% APY',
      abstract: '',
      pdfUrl: '/pdfs/lux-credit-lending.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-credit-lending.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'lending'],
    },
    {
      id: 'credit-protocol-spec',
      title: 'Lux Credit Protocol Specification: Omnichain Collateralized Credit Issuance, Transport, and Settlement',
      subtitle: 'Canonical spec for omnichain collateralized credit issuance',
      abstract: '',
      pdfUrl: '/pdfs/lux-credit-protocol-spec.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-credit-protocol-spec.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'lending'],
    },
    {
      id: 'perpetuals-derivatives',
      title: 'Lux Perpetuals: High-Leverage Derivatives with Automated Risk Management',
      subtitle: 'GMX2 integration with funding rates and liquidation engine',
      abstract: '',
      pdfUrl: '/pdfs/lux-perpetuals-derivatives.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-perpetuals-derivatives.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'dex'],
    },
    {
      id: 'liquid-staking',
      title: 'Liquid Staking on Lux: Tokenized Validator Positions with DeFi Composability',
      subtitle: 'Staked LUX derivatives with DeFi composability',
      abstract: '',
      pdfUrl: '/pdfs/lux-liquid-staking.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-liquid-staking.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    {
      id: 'restaking',
      title: 'Restaking Protocol for Lux Network Security Extension',
      subtitle: 'Shared security via validator restaking',
      abstract: '',
      pdfUrl: '/pdfs/lux-restaking.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-restaking.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    {
      id: 'omnichain-yield',
      title: 'Yield-Bearing Bridge Tokens: Cross-Chain Capital Efficiency through Composable Yield Strategies',
      subtitle: 'yLETH, yLBTC, yLUSD deploy locked bridge assets to 29 strategies',
      abstract: '',
      pdfUrl: '/pdfs/lux-omnichain-yield.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-omnichain-yield.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'yield', 'bridge'],
      relatedLinks: [
        { label: 'YieldBearingBridgeToken.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/yield/YieldBearingBridgeToken.sol' },
        { label: '29 Yield Strategies', url: 'https://github.com/luxfi/standard/tree/main/contracts/bridge/yield/strategies' },
      ],
    },
    {
      id: 'sovereign-defi',
      title: 'Sovereign DeFi: Per-Chain Governance, Shariah Compliance, and Securities-Compatible Cross-Chain Infrastructure',
      subtitle: 'Per-chain governance, Shariah compliance, and securities infrastructure',
      abstract: '',
      pdfUrl: '/pdfs/lux-sovereign-defi.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-sovereign-defi.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'governance'],
    },
    {
      id: 'oracle-infrastructure',
      title: 'Lux Oracle Infrastructure: Decentralized Price Feeds and AI-Powered Data Oracles',
      subtitle: 'AI oracle (LP-106) + traditional price feeds',
      abstract: '',
      pdfUrl: '/pdfs/lux-oracle-infrastructure.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-oracle-infrastructure.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi'],
    },
    {
      id: 'market-nft',
      title: 'Lux.market: Aggregated NFT Marketplace with Instant Liquidity',
      subtitle: 'NFT marketplace with Reservoir aggregation across 14+ chains',
      abstract: '',
      pdfUrl: '/pdfs/lux-market-nft.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-market-nft.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi'],
    },
    // ================================================================
    // Privacy
    // ================================================================
    {
      id: 'privacy-pool',
      title: 'Privacy Pools on Lux: Compliant Transaction Privacy with Association Sets',
      subtitle: 'Compliant privacy with selective disclosure',
      abstract: '',
      pdfUrl: '/pdfs/lux-privacy-pool.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-privacy-pool.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['privacy', 'zk'],
    },
    // ================================================================
    // Identity & Governance
    // ================================================================
    {
      id: 'id-iam',
      title: 'Lux.id: Decentralized Identity and Access Management for Web3',
      subtitle: 'Enterprise-grade IAM supporting OAuth 2.0, OIDC, SAML, WebAuthn',
      abstract: '',
      pdfUrl: '/pdfs/lux-id-iam.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-iam.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['did', 'iam'],
    },
    {
      id: 'id-did-specification',
      title: 'Lux ID: Decentralized Identity and Universal Access Management',
      subtitle: 'W3C-compliant DID specification for self-sovereign identity (did:lux:)',
      abstract: '',
      pdfUrl: '/pdfs/lux-id-did-specification.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-did-specification.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['did', 'iam'],
    },
    {
      id: 'governance-dao',
      title: 'Lux Governance: Unified DAO Framework for Multi-Ecosystem Coordination',
      subtitle: 'Multi-ecosystem DAO spanning Lux, Zoo, and Hanzo',
      abstract: '',
      pdfUrl: '/pdfs/lux-governance-dao.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-governance-dao.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['governance'],
    },
    {
      id: 'dao-governance-framework',
      title: 'Lux DAO: Modular Governance Framework for Decentralized Organizations',
      subtitle: 'Azorius framework with ERC6551 NFT governance',
      abstract: '',
      pdfUrl: '/pdfs/lux-dao-governance-framework.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-dao-governance-framework.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['governance'],
    },
    // ================================================================
    // Economics
    // ================================================================
    {
      id: 'economics',
      title: 'Appchain Economics: Incentive Design for Application-Specific Chains',
      subtitle: 'Economic models and fee structures for Lux appchains',
      abstract: '',
      pdfUrl: '/pdfs/lux-economics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-economics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi'],
    },
    {
      id: 'tokenomics',
      title: 'Lux Tokenomics: Economic Design for Multi-Chain Consensus Networks',
      subtitle: 'Token distribution, emission, and governance',
      abstract: '',
      pdfUrl: '/pdfs/lux-tokenomics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tokenomics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    {
      id: 'validator-economics',
      title: 'Validator Economics in Proof-of-Stake: Incentive Alignment for Lux Network',
      subtitle: 'Staking rewards, slashing, and economic security',
      abstract: '',
      pdfUrl: '/pdfs/lux-validator-economics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-validator-economics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['defi', 'staking'],
    },
    // ================================================================
    // Security & Formal Verification
    // ================================================================
    {
      id: 'master-security-model',
      title: 'Comprehensive Security Model for the Lux Network',
      subtitle: 'Four adversary classes, four protocol layers, three assumption families',
      abstract: '',
      pdfUrl: '/pdfs/lux-master-security-model.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-master-security-model.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security'],
    },
    {
      id: 'hsm-boundary',
      title: 'Secure Enclave, HSM, and Threshold Boundary Design for Validator Key Infrastructure',
      subtitle: 'Hardware security modules + threshold cryptography defense-in-depth',
      abstract: '',
      pdfUrl: '/pdfs/lux-hsm-boundary.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-hsm-boundary.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security', 'threshold', 'mpc'],
    },
    {
      id: 'zero-trust-validators',
      title: 'Zero-Trust Validator Operations and Service Identity for Blockchain Infrastructure',
      subtitle: 'Cryptographic workload identity for every service interaction',
      abstract: '',
      pdfUrl: '/pdfs/lux-zero-trust-validators.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zero-trust-validators.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security'],
    },
    {
      id: 'performance-security-tradeoffs',
      title: 'Performance vs Security Tradeoffs in Cryptographic Infrastructure',
      subtitle: 'Measured cost of every cryptographic primitive',
      abstract: '',
      pdfUrl: '/pdfs/lux-performance-security-tradeoffs.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-performance-security-tradeoffs.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security', 'pq', 'fhe', 'mpc'],
    },
    {
      id: 'proof-methodology',
      title: 'Security Proof Obligations, Red-Team Methodology, and Verification Strategy',
      subtitle: 'Lean4, Halmos, Tamarin, TLA+, Forge for every protocol component',
      abstract: '',
      pdfUrl: '/pdfs/lux-proof-methodology.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-proof-methodology.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security', 'audit', 'formal-verification'],
    },
    {
      id: 'smart-contract-auditing',
      title: 'Systematic Smart Contract Auditing: Methods and Tools',
      subtitle: 'Structured audit methodology for smart contract security',
      abstract: '',
      pdfUrl: '/pdfs/lux-smart-contract-auditing.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-smart-contract-auditing.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['security', 'audit'],
    },
    {
      id: 'formal-verification-lean4',
      title: 'Formal Verification with Lean 4 for Blockchain Systems',
      subtitle: 'Mechanized proofs of consensus and cryptographic protocol properties',
      abstract: '',
      pdfUrl: '/pdfs/lux-formal-verification-lean4.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-formal-verification-lean4.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['formal-verification', 'security'],
    },
    {
      id: 'symbolic-execution-halmos',
      title: 'Symbolic Execution for Smart Contract Verification',
      subtitle: 'Halmos-based symbolic execution for EVM bytecode analysis',
      abstract: '',
      pdfUrl: '/pdfs/lux-symbolic-execution-halmos.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-symbolic-execution-halmos.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['formal-verification', 'security', 'evm'],
    },
    {
      id: 'protocol-verification-tamarin',
      title: 'Security Protocol Verification with Tamarin Prover',
      subtitle: 'Automated verification of cryptographic protocol security properties',
      abstract: '',
      pdfUrl: '/pdfs/lux-protocol-verification-tamarin.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-protocol-verification-tamarin.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['formal-verification', 'security'],
    },
    {
      id: 'model-checking-tla',
      title: 'Model Checking Distributed Protocols with TLA+',
      subtitle: 'TLA+ specifications for consensus protocol correctness',
      abstract: '',
      pdfUrl: '/pdfs/lux-model-checking-tla.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-model-checking-tla.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['formal-verification', 'consensus'],
    },
    // ================================================================
    // Testing
    // ================================================================
    {
      id: 'distributed-systems-testing',
      title: 'Testing Distributed Systems: From Unit Tests to Jepsen',
      subtitle: 'Comprehensive testing strategy from unit tests to chaos engineering',
      abstract: '',
      pdfUrl: '/pdfs/lux-distributed-systems-testing.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-distributed-systems-testing.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['testing', 'security'],
    },
    {
      id: 'fuzz-testing-methodology',
      title: 'Property-Based Testing and Fuzzing for Cryptographic Software',
      subtitle: 'Systematic fuzzing methodology for cryptographic implementations',
      abstract: '',
      pdfUrl: '/pdfs/lux-fuzz-testing-methodology.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fuzz-testing-methodology.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['testing', 'security'],
    },
    // ================================================================
    // Roadmap & Adoption
    // ================================================================
    {
      id: 'adoption-roadmap',
      title: 'Adoption Roadmap: From Research Stack to Deployable Infrastructure',
      subtitle: 'Phased deployment from classical BLS to full Quasar triple-proof',
      abstract: '',
      pdfUrl: '/pdfs/lux-adoption-roadmap.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-adoption-roadmap.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: ['pq', 'consensus', 'fhe'],
    },
    // ================================================================
    // Cover Page
    // ================================================================
    {
      id: 'cover-lux',
      title: 'Lux Network',
      subtitle: 'Multi-consensus blockchain with post-quantum cryptography',
      abstract: '',
      pdfUrl: '/pdfs/cover-lux.pdf',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2026',
      authors: ['Lux Industries'],
      tags: [],
    },
  ],
}
