export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Lux',
  fullName: 'Lux Network',
  description: 'Post-quantum secure, high-performance blockchain infrastructure - Layer-0 for Hanzo (AI Compute) and Zoo (AI/ML Specialization)',
  website: 'https://lux.network',
  github: 'https://github.com/luxfi',
  primaryColor: '#3498DB',
  secondaryColor: '#2980B9',
  accentColor: '#E67E22',
  logo: '/logos/lux-logo.svg',
  papers: [
    {
      id: 'consensus',
      title: 'Lux Consensus',
      subtitle: 'Physics-Inspired Metastable Blockchain Consensus',
      abstract: 'Novel consensus mechanism using physics-inspired metastable dynamics for high-throughput finality.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-04-01',
      authors: ['Lux Industries'],
      tags: ['Consensus', 'Physics-Inspired', 'Metastable'],
    },
    {
      id: 'quantum-consensus',
      title: 'Quantum Consensus',
      subtitle: 'Post-Quantum Cryptography with Dilithium Signatures',
      abstract: 'Implementation of NIST-standardized Dilithium post-quantum signatures for validator consensus, ensuring security against quantum computer attacks.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-quantum-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quantum-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-06-01',
      authors: ['Lux Industries'],
      tags: ['Consensus', 'Post-Quantum', 'Cryptography', 'Dilithium'],
    },
    {
      id: 'quasar-consensus',
      title: 'Quasar Consensus',
      subtitle: 'Dual-Certificate Quantum-Secure Finality (BLS + Ringtail)',
      abstract: 'Novel consensus mechanism combining BLS signatures with post-quantum Ringtail signatures for quantum-safe finality with efficient verification.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-quasar-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quasar-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-01',
      authors: ['Lux Industries'],
      tags: ['Consensus', 'Post-Quantum', 'BLS', 'Ringtail', 'Finality'],
    },
    {
      id: 'fpc-consensus',
      title: 'FPC Consensus',
      subtitle: 'Fast Probabilistic Consensus with Adaptive Thresholds',
      abstract: 'High-throughput probabilistic consensus protocol with adaptive security thresholds and sub-second finality for optimal performance.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-fpc-consensus.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fpc-consensus.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-12-01',
      authors: ['Lux Industries'],
      tags: ['Consensus', 'Performance', 'Probabilistic', 'Low-Latency'],
    },
    {
      id: 'achain',
      title: 'A-Chain: Attestation Chain',
      subtitle: 'TEE Attestation & AI Compute Verification',
      abstract: 'Trusted Execution Environment attestation chain supporting Intel SGX, AMD SEV-SNP, NVIDIA H100 CC, and ARM CCA for verifiable AI compute.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-achain-attestation.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-achain-attestation.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-10-01',
      authors: ['Lux Industries'],
      tags: ['TEE', 'Attestation', 'AI Compute', 'SGX', 'SEV-SNP', 'H100'],
    },
    {
      id: 'gchain',
      title: 'G-Chain: GraphQL Chain',
      subtitle: 'Universal GraphQL Query Engine with BadgerDB',
      abstract: 'High-performance query layer with GraphQL API and BadgerDB storage for efficient blockchain data access and indexing.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-gchain-graphql.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-gchain-graphql.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-01',
      authors: ['Lux Industries'],
      tags: ['GraphQL', 'Indexing', 'BadgerDB', 'Query Engine'],
    },
    {
      id: 'mchain',
      title: 'M-Chain: MPC Chain',
      subtitle: 'MPC Threshold Custody (CGG21, MuSig2, FROST, Ringtail)',
      abstract: 'Multi-party computation chain for threshold custody supporting multiple protocols including post-quantum Ringtail signatures.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-mchain-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-mchain-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-15',
      authors: ['Lux Industries', 'Vishnu Seesahai'],
      tags: ['MPC', 'Threshold Signatures', 'CGG21', 'MuSig2', 'FROST'],
    },
    {
      id: 'zchain',
      title: 'Z-Chain: Zero-Knowledge Chain',
      subtitle: 'Privacy-Preserving Smart Contracts (zkEVM, FHE, TEE)',
      abstract: 'Privacy layer combining zkEVM, fully homomorphic encryption, and trusted execution environments for confidential smart contracts.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-zchain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zchain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-11-01',
      authors: ['Lux Industries'],
      tags: ['Privacy', 'zkEVM', 'FHE', 'TEE', 'Smart Contracts'],
    },
    {
      id: 'bridge',
      title: 'Lux Bridge',
      subtitle: 'Cross-Chain with ZK Light Clients & IBC Integration',
      abstract: 'Trustless cross-chain bridge using zero-knowledge light clients and IBC protocol for interoperability with Cosmos and Ethereum.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-bridge.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-bridge.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-07-01',
      authors: ['Lux Industries', 'Vishnu Seesahai'],
      tags: ['Bridge', 'IBC', 'Zero-Knowledge', 'Interoperability'],
    },
    {
      id: 'ntt',
      title: 'NTT Transform',
      subtitle: '85% Gas Reduction for Post-Quantum Crypto on EVM',
      abstract: 'Number Theoretic Transform optimization for post-quantum algorithms (FALCON, Dilithium, STARKs) achieving massive gas savings.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-ntt-transform.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ntt-transform.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-05-15',
      authors: ['Lux Industries'],
      tags: ['Post-Quantum', 'NTT', 'Gas Optimization', 'EVM'],
    },
    {
      id: 'ethfalcon',
      title: 'ETHFALCON',
      subtitle: 'Post-Quantum FALCON Signatures for Ethereum',
      abstract: 'Optimized implementation of FALCON post-quantum signatures for Ethereum, enabling quantum-safe transactions.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-ethfalcon-post-quantum.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ethfalcon-post-quantum.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-07-01',
      authors: ['Lux Industries'],
      tags: ['Post-Quantum', 'FALCON', 'Ethereum', 'Signatures'],
    },
    {
      id: 'threshold-signatures',
      title: 'Universal Threshold Signatures',
      subtitle: 'Unified Framework (CMP, FROST, LSS, Doerner, Ringtail)',
      abstract: 'Comprehensive threshold signature framework supporting multiple protocols including post-quantum Ringtail.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-universal-threshold-signatures.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-universal-threshold-signatures.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-01',
      authors: ['Lux Industries', 'Vishnu Seesahai'],
      tags: ['Threshold Signatures', 'MPC', 'Post-Quantum', 'CMP', 'FROST'],
    },
    {
      id: 'verkle',
      title: 'Verkle Trees',
      subtitle: 'Constant-Size Proofs (~150 bytes) for Stateless Clients',
      abstract: 'Implementation of Verkle trees for efficient state proofs enabling stateless client operation with minimal bandwidth.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-verkle-trees.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-verkle-trees.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-10-01',
      authors: ['Lux Industries'],
      tags: ['Verkle Trees', 'Scalability', 'Stateless', 'State Proofs'],
    },
    {
      id: 'fraud-proofs',
      title: 'Fraud Proofs',
      subtitle: 'Optimistic Rollups with Interactive Bisection Game',
      abstract: 'Optimistic rollup implementation with efficient fraud proof mechanism using interactive bisection for dispute resolution.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-fraud-proofs.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fraud-proofs.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-11-15',
      authors: ['Lux Industries'],
      tags: ['Layer 2', 'Optimistic Rollups', 'Fraud Proofs', 'Scalability'],
    },
    {
      id: 'tee-mesh',
      title: 'TEE Computing Mesh',
      subtitle: 'Distributed TEE Network for Confidential Computing',
      abstract: 'Mesh network of trusted execution environments (SGX, SEV-SNP, TDX, CCA) for distributed confidential computing.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-tee-computing-mesh.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tee-computing-mesh.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-12-01',
      authors: ['Lux Industries'],
      tags: ['TEE', 'Confidential Computing', 'SGX', 'SEV-SNP', 'TDX'],
    },
    {
      id: 'lightspeed-dex',
      title: 'Lightspeed DEX',
      subtitle: 'HFT-Optimized DEX with 261ms Latency & FPGA Matching',
      abstract: 'Ultra-low latency decentralized exchange with FPGA-accelerated order matching achieving institutional-grade performance.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-lightspeed-dex.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-lightspeed-dex.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-05-01',
      authors: ['Lux Industries'],
      tags: ['DeFi', 'DEX', 'HFT', 'FPGA', 'Low-Latency'],
    },
    {
      id: 'credit',
      title: 'Lux Credit',
      subtitle: 'Self-Repaying Lending with 90% LTV & 11% APY',
      abstract: 'Novel lending protocol with self-repaying mechanism, high loan-to-value ratios, and attractive yields on LUX staking.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-credit-lending.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-credit-lending.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-15',
      authors: ['Lux Industries'],
      tags: ['DeFi', 'Lending', 'Credit', 'Self-Repaying'],
    },
    {
      id: 'oracle',
      title: 'Oracle Infrastructure',
      subtitle: 'AI Oracle (LP-106) + Traditional Price Feeds',
      abstract: 'Hybrid oracle system combining AI-powered LP-106 protocol with Chainlink and Pyth for reliable price feeds.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-oracle-infrastructure.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-oracle-infrastructure.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-09-01',
      authors: ['Lux Industries'],
      tags: ['Oracle', 'AI', 'Price Feeds', 'Chainlink', 'Pyth'],
    },
    {
      id: 'perpetuals',
      title: 'Perpetuals & Derivatives',
      subtitle: 'GMX2 Integration with Funding Rates & Liquidation Engine',
      abstract: 'Perpetual futures and derivatives platform integrated with GMX v2 architecture for advanced trading capabilities.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-perpetuals-derivatives.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-perpetuals-derivatives.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-10-15',
      authors: ['Lux Industries'],
      tags: ['DeFi', 'Perpetuals', 'Derivatives', 'GMX', 'Trading'],
    },
    {
      id: 'market',
      title: 'Lux.market NFT',
      subtitle: 'NFT Marketplace with Reservoir Aggregation',
      abstract: 'Multi-chain NFT marketplace aggregating liquidity from 14+ chains using Reservoir protocol for optimal pricing.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-market-nft.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-market-nft.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-07-15',
      authors: ['Lux Industries'],
      tags: ['NFT', 'Marketplace', 'Reservoir', 'Multi-Chain'],
    },
    {
      id: 'id-iam',
      title: 'Lux ID IAM',
      subtitle: 'Identity & Access Management',
      abstract: 'Enterprise-grade identity and access management supporting OAuth 2.0, OIDC, SAML, WebAuthn, and multi-factor authentication.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-id-iam.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-iam.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-06-15',
      authors: ['Lux Industries'],
      tags: ['Identity', 'IAM', 'OAuth', 'WebAuthn', 'SSO'],
    },
    {
      id: 'id-did',
      title: 'Lux ID DID Specification',
      subtitle: 'Decentralized Identifiers (did:lux:)',
      abstract: 'W3C-compliant DID specification for Lux Network enabling self-sovereign identity and verifiable credentials.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-id-did-specification.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-did-specification.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-06-20',
      authors: ['Lux Industries'],
      tags: ['DID', 'Identity', 'W3C', 'Verifiable Credentials'],
    },
    {
      id: 'governance',
      title: 'Governance & DAO',
      subtitle: 'Multi-Ecosystem DAO (Lux, Zoo, Hanzo)',
      abstract: 'Holographic consensus-based governance spanning Lux, Zoo, and Hanzo ecosystems for unified decision-making.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-governance-dao.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-governance-dao.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-01',
      authors: ['Lux Industries'],
      tags: ['Governance', 'DAO', 'Holographic Consensus', 'Multi-Ecosystem'],
    },
    {
      id: 'dao-framework',
      title: 'DAO Governance Framework',
      subtitle: 'Azorius Framework with ERC6551 NFT Governance',
      abstract: 'Advanced DAO governance using Azorius framework with ERC6551 token-bound accounts for NFT-based voting.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-dao-governance-framework.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-dao-governance-framework.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-08-15',
      authors: ['Lux Industries'],
      tags: ['DAO', 'Governance', 'Azorius', 'ERC6551', 'NFT'],
    },
    {
      id: 'data-availability',
      title: 'Data Availability Layer',
      subtitle: 'Erasure Coding and KZG Commitments',
      abstract: 'Data availability layer using erasure coding and KZG commitments for scalable blockchain data guarantees.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-data-availability.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-data-availability.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Data Availability', 'Erasure Coding', 'KZG', 'Scalability'],
    },
    {
      id: 'economics',
      title: 'Lux Network Economics',
      subtitle: 'Appchain Economic Models and Fee Structures',
      abstract: 'Economic models and fee structures for Lux Network appchains and the broader ecosystem.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-economics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-economics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Economics', 'Appchain', 'Fee Structure', 'Tokenomics'],
    },
    {
      id: 'evm-precompiles',
      title: 'EVM Precompiles for Post-Quantum Cryptography',
      subtitle: 'Native Post-Quantum Operations in EVM',
      abstract: 'EVM precompiles enabling native post-quantum cryptographic operations for efficient on-chain verification.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-evm-precompiles.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-evm-precompiles.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['EVM', 'Precompiles', 'Post-Quantum', 'Cryptography'],
    },
    {
      id: 'interchain-transfers',
      title: 'Interchain Transfer Protocol',
      subtitle: 'Cross-Chain Asset Transfers with Atomic Guarantees',
      abstract: 'Cross-chain asset transfer protocol with atomic guarantees for secure interchain operations.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-interchain-transfers.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-interchain-transfers.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Interchain', 'Cross-Chain', 'Atomic', 'Transfers'],
    },
    {
      id: 'liquid-staking',
      title: 'Liquid Staking Protocol',
      subtitle: 'Staked LUX Derivatives with DeFi Composability',
      abstract: 'Liquid staking protocol for LUX with DeFi-composable staked derivatives.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-liquid-staking.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-liquid-staking.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Liquid Staking', 'DeFi', 'Staking', 'Derivatives'],
    },
    {
      id: 'privacy-pool',
      title: 'Privacy Pool Protocol',
      subtitle: 'Compliant Privacy with Selective Disclosure',
      abstract: 'Privacy pool protocol combining compliant privacy with selective disclosure using zero-knowledge proofs.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-privacy-pool.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-privacy-pool.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Privacy', 'ZK Proofs', 'Compliance', 'Selective Disclosure'],
    },
    {
      id: 'restaking',
      title: 'Restaking Protocol',
      subtitle: 'Shared Security via Validator Restaking',
      abstract: 'Restaking protocol enabling shared security through validator restaking across multiple networks.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-restaking.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-restaking.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Restaking', 'Shared Security', 'Validators', 'EigenLayer'],
    },
    {
      id: 'state-sync',
      title: 'State Synchronization Protocol',
      subtitle: 'Fast State Sync with Merkle Range Proofs',
      abstract: 'Fast state synchronization protocol using Merkle range proofs for efficient node bootstrapping.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-state-sync.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-state-sync.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['State Sync', 'Merkle Proofs', 'Performance', 'Networking'],
    },
    {
      id: 'tokenomics',
      title: 'LUX Tokenomics',
      subtitle: 'Token Distribution, Emission, and Governance',
      abstract: 'LUX token distribution, emission schedule, and governance mechanisms for the Lux Network.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-tokenomics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tokenomics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Tokenomics', 'Token Distribution', 'Emission', 'Governance'],
    },
    {
      id: 'validator-economics',
      title: 'Validator Economics',
      subtitle: 'Staking Rewards, Slashing, and Economic Security',
      abstract: 'Validator economics covering staking rewards, slashing conditions, and economic security guarantees.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-validator-economics.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-validator-economics.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Validators', 'Economics', 'Staking', 'Slashing'],
    },
    {
      id: 'warp-messaging',
      title: 'Warp Messaging Protocol',
      subtitle: 'Native Cross-Chain Messaging',
      abstract: 'Native cross-chain messaging protocol for efficient inter-subnet communication on Lux Network.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-warp-messaging.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-warp-messaging.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2025-02-20',
      authors: ['Lux Industries'],
      tags: ['Warp', 'Messaging', 'Cross-Chain', 'Communication'],
    },
    // ================================================================
    // NEW: Teleport Omnichain Suite (2022-2025)
    // ================================================================
    {
      id: 'teleport-omnichain',
      title: 'Lux Teleport: Sovereign Omnichain Liquidity',
      subtitle: 'Non-Custodial Cross-Chain Asset Transfer via Threshold Cryptography',
      abstract: 'Non-custodial omnichain bridge connecting 20 execution environments and 270+ blockchains through unified MPC threshold signatures. Introduces sovereign per-chain governance, yield-bearing bridge tokens with 29 strategies, and Shariah-compliant DeFi mode. Supersedes Teleport Protocol (2022) and Bridge (2023).',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-teleport-omnichain.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-teleport-omnichain.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2022-09-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['Bridge', 'Teleport', 'Omnichain', 'MPC', 'FROST', 'Governance', 'Yield', 'Shariah'],
      relatedLinks: [
        { label: 'OmnichainRouter.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/OmnichainRouter.sol' },
        { label: 'ChainIds.sol (270 chains)', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/chains/ChainIds.sol' },
        { label: 'Formal Proofs', url: 'https://proofs.lux.network' },
      ],
    },
    {
      id: 'threshold-mpc',
      title: 'Unified Threshold Cryptography for Omnichain Custody',
      subtitle: 'FROST, CGGMP21, and Taproot Integration',
      abstract: 'Complete treatment of the threshold signature system: FROST (Ed25519/Schnorr) for 14 chain families, CGGMP21 (ECDSA) for 6 chain families, Bitcoin Taproot via KeygenTaproot. Includes 9 theorems, 3 lemmas, 8 algorithms, formal unforgeability proofs. Supersedes Universal Threshold Signatures (2021) and MPC (2023).',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-threshold-mpc.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-threshold-mpc.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2021-02-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['FROST', 'CGGMP21', 'Taproot', 'Threshold', 'MPC', 'Ed25519', 'ECDSA', 'Formal Proofs'],
      relatedLinks: [
        { label: 'luxfi/threshold (Go)', url: 'https://github.com/luxfi/threshold' },
        { label: 'luxfi/mpc (Go)', url: 'https://github.com/luxfi/mpc' },
        { label: 'FROST Precompile', url: 'https://github.com/luxfi/standard/tree/main/src/precompiles/frost' },
      ],
    },
    {
      id: 'omnichain-yield',
      title: 'Yield-Bearing Bridge Tokens',
      subtitle: 'Cross-Chain Capital Efficiency through Composable Yield Strategies',
      abstract: '$15B+ locked in bridges earning zero yield. Yield-bearing bridge tokens (yLETH, yLBTC, yLUSD) deploy locked assets to 29 strategies across 9 categories. Share-price monotonicity proof, auto-pause on undercollateralization, xLUX flywheel economics. First Bitcoin-native yield composition (Babylon + Lombard + SolvBTC).',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-omnichain-yield.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-omnichain-yield.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2024-12-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['Yield', 'Bridge', 'ERC-4626', 'Lido', 'EigenLayer', 'Babylon', 'Bitcoin', 'xLUX'],
      relatedLinks: [
        { label: 'YieldBearingBridgeToken.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/yield/YieldBearingBridgeToken.sol' },
        { label: '29 Yield Strategies', url: 'https://github.com/luxfi/standard/tree/main/contracts/bridge/yield/strategies' },
        { label: 'LiquidLUX (xLUX)', url: 'https://github.com/luxfi/standard/blob/main/contracts/liquid/LiquidLUX.sol' },
      ],
    },
    {
      id: 'sovereign-defi',
      title: 'Sovereign DeFi',
      subtitle: 'Per-Chain Governance, Shariah Compliance, and Securities Infrastructure',
      abstract: 'Sovereign governance model where each chain controls its own bridge economics. Governance isolation theorem (governor cannot mint). First protocol-level Shariah compliance for DeFi (ShariaFilter contract, SAB multisig). ERC-3643 securities compliance with settlement registry. Nash equilibrium fee competition analysis.',
      pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-sovereign-defi.pdf',
      latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-sovereign-defi.tex',
      githubUrl: 'https://github.com/luxfi/papers',
      date: '2022-01-01',
      authors: ['Zach Kelling', 'Vishnu Seesahai'],
      tags: ['Governance', 'Shariah', 'Islamic Finance', 'Securities', 'ERC-3643', 'Compliance', 'DAO'],
      relatedLinks: [
        { label: 'OmnichainRouter.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/OmnichainRouter.sol' },
        { label: 'ShariaFilter.sol', url: 'https://github.com/luxfi/standard/blob/main/contracts/bridge/yield/ShariaFilter.sol' },
        { label: 'Formal Proofs', url: 'https://proofs.lux.network' },
      ],
    },
  ],
}
